# AUTOGENERATED FROM 'queries/get_session.edgeql' WITH:
#     $ gel-py --dsn gel://test:test@localhost:5656/main --tls-security insecure


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetSessionResult(NoPydanticValidation):
    id: uuid.UUID
    chat_id: str
    messages: str
    created_at: datetime.datetime
    updated_at: datetime.datetime | None


async def get_session(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: str,
) -> GetSessionResult | None:
    return await executor.query_single(
        """\
        select Session {
            id,
            chat_id,
            messages,
            created_at,
            updated_at
        }
        filter .chat_id = <str>$chat_id
        limit 1;\
        """,
        chat_id=chat_id,
    )
