# AUTOGENERATED FROM 'queries/update_session.edgeql' WITH:
#     $ gel-py --dsn gel://test:test@localhost:5656/main --tls-security insecure


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateSessionResult(NoPydanticValidation):
    id: uuid.UUID
    chat_id: str
    messages: str
    updated_at: datetime.datetime | None


async def update_session(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: str,
    messages: str,
) -> list[UpdateSessionResult]:
    return await executor.query(
        """\
        with 
            chat_id := <str>$chat_id,
            messages := <json>$messages

        select (
            update Session 
            filter .chat_id = chat_id
            set {
                messages := messages,
                updated_at := datetime_current()
            }
        ) {
            id,
            chat_id,
            messages,
            updated_at
        };\
        """,
        chat_id=chat_id,
        messages=messages,
    )
