name: Release
on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - "pyproject.toml"
      - "uv.lock"
      - "Dockerfile"
      - ".github/**"
      - "run.py"

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.13"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --dev

      - name: Run ruff
        run: uv run ruff check .

      - name: Run mypy
        run: uv run mypy .

  docker:
    runs-on: ubuntu-24.04
    needs: check
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/eat-and-run:latest
